# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

development:
  adapter: mysql2
  encoding: utf8
  database: XTick_development
  pool: 5
  username: root
  password: root
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: XTick_test
  pool: 5
  username: root
  password: root
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: pg
  encoding: utf8
  database: dat6ntvsrnmdbd
  pool: 5
  username: ccpbnodsgsbirj
  password: 5432
  host: ec2-23-21-129-125.compute-1.amazonaws.com
  socket: /var/run/mysqld/mysqld.sock
